---
format: 
  docx:
    reference-doc: my_styles.docx
    number-sections: true
title: "*Supplement* Managing the unmanageable: Understanding the competing effects of salinity and nutrient loading on estuarine water quality"
bibliography: refs.bib
csl: estuaries-and-coasts.csl
crossref: 
  fig-title: Fig.
author:
  - Marcus W Beck:
      email: mbeck@tbep.org
      orcid: 0000-0002-4996-0059
      institute: [TBEP]
      correspondence: true
  - Rebecca Murphy:
      email: rmurphy@chesapeakebay.net
      orcid: 0000-0003-3391-1823
      institute: [CBP]
      correspondence: false
  - Kerry Flaherty-Walia:
      email: kfwalia@tbep.org
      orcid: 0000-0002-6032-0570
      institute: [TBEP]
      correspondence: false
  - Qian Zhang:
      email: qzhang@chesapeakebay.net
      orcid: 0000-0003-0500-5655
      institute: [CBP]
      correspondence: false
  - Blake A Simmons: 
      email: bsimmons@tbep.org
      orcid: 0000-0002-1918-3463
      institute: [TBEP]
      correspondence: false
  - Maya C Burke:
      email: mburke@tbep.org
      orcid: 0000-0002-3847-6501      
      institute: [TBEP]
      correspondence: false 
  - Edward T Sherwood:
      email: esherwood@tbep.org
      orcid: 0000-0001-5330-302X
      institute: [TBEP]
      correspondence: false

institute:
  - TBEP: Tampa Bay Estuary Program, 263 13th Ave S., Suite 350, St. Petersburg, Florida 33701 USA
  - CBP: University of Maryland Center for Environmental Science/U.S. Environmental Protection Agency Chesapeake Bay Program, 1750 Forest Drive, Annapolis, Maryland 21401 USA

filters: 
  - templates/scholarly-metadata.lua
  - templates/author-info-blocks.lua
  
execute: 
  echo: false
  warning: false
  ft.keepnext: false
  ft.align: left
---

```{r}
#| results: hide
library(knitr)
library(here)
library(flextable)

load(file = here('tabs/suppgamtab.RData'))
load(file = here('tabs/suppconcurvotbtab.RData'))
load(file = here('tabs/suppconcurvhbtab.RData'))
load(file = here('tabs/suppconcurvmtbtab.RData'))
load(file = here('tabs/suppconcurvltbtab.RData'))
```

{{< pagebreak >}}

## Tables {.unnumbered}

```{r}
#| label: tbl-supgamtab
#| tbl-cap: "Generalized Additive Model (GAM) summary statistics for chlorophyll-a predictions by bay segment in Tampa Bay (n = 480 for each).  Results are shown for models with different total nitrogen loading lags, whether salinity or loading were corrected for seasonality, and constraints on the number of smoothers (K) for time, loading, and salinity (flexible or fixed). Loads were evaluated as cumulative sums for the current month up to a three month lag. Results for the overall model fit are shown with the Generalized Cross Validation (GCV) scores in the top rows and deviance explained (Dev. Expl.) in the bottom rows. OTB: Old Tampa Bay; HB: Hillsborough Bay; MTB: Middle Tampa Bay; LTB: Lower Tampa Bay."
suppgamtab
```

{{< pagebreak >}}

```{r}
#| label: tbl-supconcurvotbtab
#| tbl-cap: "Concurvity estimates for the __Old Tampa Bay__ Generalized Additive Models.  Values range from 0 to 1 and assess the degree of multicollinearity among predictors. Values are shown for only the smooth functions of time (dec_time), salinity (sal), and total nitrogen loading (tn_load). The smooth function for day of year and tensor product smooths are omitted and had values all less than those shown. Results are shown for models with different total nitrogen loading lags, whether salinity or loading were corrected for seasonality, and constraints on the number of smoothers (K) for time, loading, and salinity (flexible or fixed). Loads were evaluated as cumulative sums for the current month up to a three month lag. Font size and shading are proportional among cells to emphasize differences."
suppconcurvotbtab
```

{{< pagebreak >}}

```{r}
#| label: tbl-supconcurvhbtab
#| tbl-cap: "Concurvity estimates for the __Hillsborough Bay__ Generalized Additive Models.  Values range from 0 to 1 and assess the degree of multicollinearity among predictors. Values are shown for only the smooth functions of time (dec_time), salinity (sal), and total nitrogen loading (tn_load). The smooth function for day of year and tensor product smooths are omitted and had values all less than those shown. Results are shown for models with different total nitrogen loading lags, whether salinity or loading were corrected for seasonality, and constraints on the number of smoothers (K) for time, loading, and salinity (flexible or fixed). Loads were evaluated as cumulative sums for the current month up to a three month lag. Font size and shading are proportional among cells to emphasize differences."
suppconcurvhbtab
```

{{< pagebreak >}}

```{r}
#| label: tbl-supconcurvmtbtab
#| tbl-cap: "Concurvity estimates for the __Middle Tampa Bay__ Generalized Additive Models.  Values range from 0 to 1 and assess the degree of multicollinearity among predictors. Values are shown for only the smooth functions of time (dec_time), salinity (sal), and total nitrogen loading (tn_load). The smooth function for day of year and tensor product smooths are omitted and had values all less than those shown. Results are shown for models with different total nitrogen loading lags, whether salinity or loading were corrected for seasonality, and constraints on the number of smoothers (K) for time, loading, and salinity (flexible or fixed). Loads were evaluated as cumulative sums for the current month up to a three month lag. Font size and shading are proportional among cells to emphasize differences."
suppconcurvmtbtab
```

{{< pagebreak >}}

```{r}
#| label: tbl-supconcurvltbtab
#| tbl-cap: "Concurvity estimates for the __Lower Tampa Bay__ Generalized Additive Models.  Values range from 0 to 1 and assess the degree of multicollinearity among predictors. Values are shown for only the smooth functions of time (dec_time), salinity (sal), and total nitrogen loading (tn_load). The smooth function for day of year and tensor product smooths are omitted and had values all less than those shown. Results are shown for models with different total nitrogen loading lags, whether salinity or loading were corrected for seasonality, and constraints on the number of smoothers (K) for time, loading, and salinity (flexible or fixed). Loads were evaluated as cumulative sums for the current month up to a three month lag. Font size and shading are proportional among cells to emphasize differences."
suppconcurvltbtab
```