---
format: 
  docx:
    reference-doc: response_styles.docx
bibliography: ../refs.bib
csl: ../estuaries-and-coasts.csl

execute: 
  echo: false
  warning: false
  message: false
---

```{r}
#| eval: false
spelling::spell_check_files(here::here('revision/review_response.qmd'))
```

*We sincerely thank the editors and all reviewers for providing useful comments on our manuscript. We have made every effort to address these concerns. In particular, we have..... Please see the responses below (line numbers in responses refer to the revised manuscript).*

### Reviewer #1:

1\. Ln 180: It seems like it would be more relevant to the analysis of chlorophyll-a to analyze surface salinity, rather than averaging across all depths. Additional rationale should be given to justify this choice. Does interpretation of model output change if surface salinity rather than depth-averaged salinity is used? By including bottom salinity, is there greater aliasing of tidal variability in the monthly salinity data? Or is this accounted for during the cruise surveys (e.g., sampling at similar tidal stage across all cruises)?

*response*

2\. For the "futures" scenario, linear regression is used to empirically estimate future salinity. However, for the loading, it's more of a sensitivity analysis approach, where the TMDL threshold is either halved or doubled. What is the justification for the choice of loading scenarios, rather than assuming long-term observed trends in loading will continue over the next 50 years? This is obviously unlikely if the decrease in load was due to one-time WWTP upgrades, but I think the choice still warrants further explanation as halving the load specified in the TMDL may also be an equally unlikely scenario depending on source, available BMPs, etc...

*response*

3\. Section 3.2: the value added by the salinity-normalized and salinity-normalized at mean loading is not immediately obvious. For example, lines 379 - 380 state "suggesting that salinity and/or loading were key drivers of chlorophyll-a that varied over time". Isn't that already previously inferred from Table 1 and the fact that salinity and interactions between loading and other variables uniquely explain deviance observed in chlorophyll-a? MTB and LTB did not have significant interactions between loading and other variables (Table 1), whereas HB and OTB did, and these are the segments where, "salinity-normalized results were similar to those at mean loading. This suggested that loading had more unique effects on chlorophyll-a in OTB and HB, whereas a loading effect could not be distinguished from salinity for MTB and LTB" (lines 383 - 386). The methodological description (section 2.3) and figures for the salinity-normalized results are a bit convoluted, while seemingly redundant of the findings of the original GAM. I think the motivation was to apply a WRTDS-like approach (Beck & Hagy, 2015) within a GAM framework but I'm not convinced that it enhances the findings of the paper.
 
*response* 

4\. Discussion: The relevance of the results regarding future changes in chlorophyll-a are limited by the fact that the authors didn't consider changes in temperature, which often has a first order effect on algal dynamics. If the salinity-normalized results were removed from the paper, it would allow for the concurrent effects of temperature and salinity to be modeled and discussed, which would strengthen the results/discussion regarding projected changes in chlorophyll-a.

*response* 

Specific Comments

1\. Ln 55: missing period before "similarly"

*Added.* 

2\. Ln 117: for conciseness consider changing to "freshwater inflows and circulation".

*Changed.* 

3\. Ln 141: Consider adding bathymetry data to Figure 1 (if available) to accompany description

*Bathymetry was added to the figure, in addition to some legend items to make the elements more readable.* 

4\. Ln 149: Add reference to Figure 2.

*The loading data in Figure 2 begins in 1985 and does not provide a comparison to those from the 1970s "worst-case" scenario.  We have added a citation to the historical document from which those estimates were obtained and the current for comparison [@tbep0494; @janicki23].*

5\. Consider moving the last paragraph in methods (ln 158 - 175) to the introduction.

*This paragraph was moved to the second to last paragraph of the introduction.* 

6\. Ln 213- 215: Add a citation to show this is a previously documented approach for dealing with long-term change as well as seasonal variability in the time component. 

*A citation to @beck2022b was added since this was the origin of the concept.* 

7\. Ln 227 - 229: the justification for assuming a gamma distribution should be elaborated further

*Text was added about justification for the distribution and a table showing a comparison of Gaussian/log-link with the existing Gamma models was included in supplement.*
 
*"Models using a Gaussian distribution with a log-link function were also evaluated, although using a Gamma distribution was superior when compared with Akaike information criterion [@akaike1974, Table S1]."* 

8\. Ln 269: minimum and maximum observed over what time-period?

*response* 

9\. Ln 274: over what time period was the mean loading computed?

*Text was modified to "minimum and maximum * 

10\. Ln 322: Are the chlorophyll-a thresholds defined in FDEP's water quality standards? It would be helpful to clarify where these numbers come from. Citing Figure 2, which shows the relevant regulatory criteria would likely be sufficient.

*response* 

11\. Ln 349: Is the lower percent explained in LTB due to aliasing of tidal variability in salinity data since the data was depth-averaged?

*response* 

12\. Ln 353 - 356: I believe this is determined by the p-value, which should be clarified in the text.

*response* 

13\. Ln 365 - 367: Is this because the water column is less stratified? Or because there is less episodic variation in the load, which decreases the likelihood of aliasing higher frequency variability due to storms? In general, some of the trends in model-data agreement across segments are not particularly surprising given the model setup.

*response* 

14\. Figure 5: Consider showing the effect plots for the original GAM instead of the salinity-normalized analysis.

*response* 

15\. Figure 6: Consider making the x- and y-axis scales the same for the different segments because the e.g., stronger loading effect in OTB/HB isn't immediately obvious. Also, are the lines necessary since the points are color-coded? You could instead use a color gradient to represent year as in Figure 3. This would lessen the need to have year labels, which should be described in the caption if included.

*response* 

16\. Ln 554-55: Is high salinity attributable to high tidal exchange given the monthly data doesn't resolve tidal variability? Or is it that the salinity is higher during the dry season? (this explanation seems more consistent with the sentences that follow).

*response* 

### Reviewer #2:

The authors build a Generalized Additive Models (GAMs) to model chlorophyll-a as a function of time, salinity, nutrient load and their derivative to understand historical relationship as well as project future potential management actions that may be needed in Old Tampa Bay, Florida, USA.

The paper has a clear objective, analysis and conclusion to support the findings. My main concern is the lack of Exploratory Data Analysis (EDA) to not only justify the model but provide readers with potential transferability contribution to other areas of the world. Even leaving out other variables that may explain chlorophyll-a, there was no justification as to the form of preselected variables. On Line 220- 222, the authors say, "no efforts were made for carriable section since the same model structure for describing drivers and scenario testing between bay segments was desired (objective 2 and (3)". There is an issue in this statement, because it implies that as long as one is interested in potential differences (between historical and some future time of a variable), how one came up with the model has less influence. In addition, the justification to say what is done is what is mentioned in the objective seems difficult reasoning to follow. Yes, it is important to address what is promised in the objective, but if the objective needs to be relaxed to put EDA in the work, I would suggest it should be.

*response* 

Other minor comments are 1) Given the lack of documented EDA, I am not sure about the value of two-time variables. Both are basically taking care of seasonality. The same is true with interaction terms. What are the justifications for those terms? 2) Line 68 to 70 says "This study is an explicit follow-up to Beck et al. (2024) by providing a quantitative assessment of the relative risk of exceeding regulatory standards under future climate change." I did not see any analysis support for this statement. Please include supporting material or remove it.
Overall, this is a great study and could be improved by adding some form of EDA that readers can take away from this study.

*response* 

## References